location_master:
    image: elasticsearch:2.4-alpine
    command: "elasticsearch -Des.cluster.name=locations -Des.node.master=true -Des.node.data=false"
    volumes:
      - "/home/elasticsearch_snapshots:/usr/share/elasticsearch/snapshots"
    environment:
       - ES_HEAP_SIZE=24g
    ports:
      - "127.0.0.1:19200:9200"
      - "127.0.0.1:19300:9300"
    restart: always
location_node_1:
    image: elasticsearch:2.4-alpine
    command: "elasticsearch -Des.cluster.name=locations -Des.discovery.zen.ping.unicast.hosts=location_master"
    links:
      - location_master
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=24g
    restart: always
location_node_2:
    image: elasticsearch:2.4-alpine
    command: "elasticsearch -Des.cluster.name=locations -Des.discovery.zen.ping.unicast.hosts=location_master"
    links:
      - location_master
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=24g
    restart: always
recruitment_master:
    image: elasticsearch:2.4.6-alpine
    command: "elasticsearch -Des.cluster.name=recruitment -Des.node.master=true -Des.node.data=false"
    environment:
       - ES_HEAP_SIZE=16g
    ports:
      - "127.0.0.1:18200:9200"
      - "127.0.0.1:18300:9300"
    restart: always
recruitment_node_1:
    image: elasticsearch:2.4.6-alpine
    command: "elasticsearch -Des.cluster.name=recruitment -Des.discovery.zen.ping.unicast.hosts=recruitment_master"
    links:
      - recruitment_master
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=17g
    restart: always
recruitment_node_2:
    image: elasticsearch:2.4.6-alpine
    command: "elasticsearch -Des.cluster.name=recruitment -Des.discovery.zen.ping.unicast.hosts=recruitment_master"
    links:
      - recruitment_master
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=16g
    restart: always

solr:
    image: nodextechnology/solr:5.1
    restart: always
    ports:
      - "127.0.0.1:8983:8983"
      - "127.0.0.1:8080:8080"
    command: "/usr/bin/java -Xms4g -Xmx4g  -Xloggc:/opt/solr/server/solr/logs/solr_gc.log
  -Djetty.port=8080 -DSTOP.PORT=7080 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -Dsolr.solr.home=/opt/solr/server/solr -Dsolr.install.dir=/opt/solr/server -Dlog4j.configuration=file:/opt/solr/server/solr/log4j.properties -jar /opt/solr/server/start.jar"
    volumes:
      - "/home/solr:/opt/solr/server/solr"

tika:
  image: nodextechnology/tika:latest
  restart: always
  ports:
    - "127.0.0.1:9998:9998"

mongodb:
  image: nodextechnology/mongodb:3.6
  ports:
    - "127.0.0.1:27017:27017"
  volumes:
    - /home/mongodb:/data/db
  restart: always

elasticsearch_9200:
    image: nodextechnology/elasticsearch:1.7.6
    command: "elasticsearch -Des.cluster.name=general"
    environment:
       - ES_HEAP_SIZE=8g
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - "/home/elasticsearch/legacy_9200:/usr/share/elasticsearch/data"
      - "/home/elasticsearch_snapshots:/usr/share/elasticsearch/snapshots"
    restart: always