locations:
    image: nodextechnology/elasticsearch:2.4.6-alpine
    container_name: locations
    command: "elasticsearch"
    volumes:
      - "/home/elasticsearch_snapshots/locations:/usr/share/elasticsearch/snapshots"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
       - ES_HEAP_SIZE=24g
       - network.host=0.0.0.0
       - node.master=true
       - node.data=false
       - cluster.name=locations
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms24g -Xmx24g"
       - path.repo=["/usr/share/elasticsearch/snapshots"]
       - http.max_content_length=1000mb
       - script.engine.groovy.inline.aggs=on
    ports:
      - "127.0.0.1:19200:9200"
      - "127.0.0.1:19300:9300"
    restart: always
location1:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    image: nodextechnology/elasticsearch:2.4.6-alpine
    container_name: location1
    command: "elasticsearch"
    links:
      - locations
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
         - ES_HEAP_SIZE=24g
         - network.host=0.0.0.0
         - cluster.name=locations
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms24g -Xmx24g"
         - discovery.zen.ping.unicast.hosts=locations
    restart: always
location2:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    container_name: location2
    image: nodextechnology/elasticsearch:2.4.6-alpine
    command: "elasticsearch"
    links:
      - locations
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - ES_HEAP_SIZE=24g
      - network.host=0.0.0.0
      - cluster.name=locations
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms24g -Xmx24g"
      - discovery.zen.ping.unicast.hosts=locations
    restart: always
recruitment:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    container_name: recruitment
    image: nodextechnology/elasticsearch:2.4.6-alpine
    command: "elasticsearch"
    volumes:
        - "/home/elasticsearch_snapshots/recruitment:/usr/share/elasticsearch/snapshots"
    environment:
        - ES_HEAP_SIZE=16g
        - node.master=true
        - node.data=false
        - network.host=0.0.0.0
        - cluster.name=recruitment
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
        - http.max_content_length=1000mb
        - script.engine.groovy.inline.aggs=on
    ports:
      - "127.0.0.1:18200:9200"
      - "127.0.0.1:18300:9300"
    restart: always
recruitment1:
    container_name: recruitment1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    image: nodextechnology/elasticsearch:2.4.6-alpine
    command: "elasticsearch"
    links:
      - recruitment
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - ES_HEAP_SIZE=16g
      - network.host=0.0.0.0
      - cluster.name=recruitment
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - discovery.zen.ping.unicast.hosts=recruitment
      - path.repo=["/usr/share/elasticsearch/snapshots"]
    restart: always
recruitment2:
    container_name: recruitment2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    image: nodextechnology/elasticsearch:2.4.6-alpine
    command: "elasticsearch"
    links:
      - recruitment
    volumes:
      - "/home/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - ES_HEAP_SIZE=16g
      - network.host=0.0.0.0
      - cluster.name=recruitment
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - discovery.zen.ping.unicast.hosts=recruitment
    restart: always

solr:
    image: nodextechnology/solr:5.1
    restart: always
    ports:
      - "127.0.0.1:8983:8983"
      - "127.0.0.1:8080:8080"
    command: "/usr/bin/java -Xms4g -Xmx4g  -Xloggc:/opt/solr/server/solr/logs/solr_gc.log
  -Djetty.port=8080 -DSTOP.PORT=7080 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -Dsolr.solr.home=/opt/solr/server/solr -Dsolr.install.dir=/opt/solr/server -Dlog4j.configuration=file:/opt/solr/server/solr/log4j.properties -jar /opt/solr/server/start.jar"
    volumes:
      - "/home/solr:/opt/solr/server/solr"

tika:
  image: nodextechnology/tika:latest
  restart: always
  ports:
    - "127.0.0.1:9998:9998"

mongodb:
  image: nodextechnology/mongodb:3.6
  ports:
    - "127.0.0.1:27017:27017"
  volumes:
    - /home/mongodb:/data/db
  restart: always

elasticsearch_9200:
    image: nodextechnology/elasticsearch:1.7.6-alpine
    command: "elasticsearch"
    environment:
       - ES_HEAP_SIZE=8g
       - cluster.name=legacy
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - "/home/elasticsearch/legacy_9200:/usr/share/elasticsearch/data"
      - "/home/elasticsearch_snapshots/legacy:/usr/share/elasticsearch/snapshots"
    restart: always